name: may_be_clean
description: A new Flutter project.
publish_to: "none"

version: 1.0.2+19

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  google_maps_flutter: ^2.2.3
  flutter_svg: ^2.0.0+1
  fluttertoast: ^8.1.2
  path_provider: ^2.0.15
  path: ^1.8.3
  carousel_slider: ^4.2.1
  http: ^0.13.5
  dio: ^5.0.1
  shared_preferences: ^2.0.18
  geolocator: ^9.0.0
  tuple: ^2.0.1
  readmore: ^2.2.0
  cached_network_image: ^3.2.3
  kakao_flutter_sdk: ^1.4.3
  sign_in_with_apple: ^4.3.0
  image_picker: ^0.8.7+5
  mime: ^1.0.4
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/splash/
    - assets/icons/
    - assets/icons/navigation/
    - assets/icons/category/
    - assets/images/
    - assets/icons/clover/
    - assets/icons/review/
    - assets/icons/map/
    - assets/icons/badge/
    - assets/icons/login/
    - assets/icons/marker/
    - assets/icons/store/
fonts:
  - family: pretendard
    fonts:
      - asset: assets/fonts/Pretendard-Regular.otf
      - asset: assets/fonts/Pretendard-Thin.otf
        weight: 100
      - asset: assets/fonts/Pretendard-ExtraLight.otf
        weight: 200
      - asset: assets/fonts/Pretendard-Light.otf
        weight: 300
      - asset: assets/fonts/Pretendard-Regular.otf
        weight: 400
      - asset: assets/fonts/Pretendard-Medium.otf
        weight: 500
      - asset: assets/fonts/Pretendard-SemiBold.otf
        weight: 600
      - asset: assets/fonts/Pretendard-Bold.otf
        weight: 700
      - asset: assets/fonts/Pretendard-ExtraBold.otf
        weight: 800
      - asset: assets/fonts/Pretendard-Black.otf
        weight: 900
